services:
  watchtower-api:
    build:
      context: ./watchtower
      dockerfile: database/Dockerfile.api
      network: host
    container_name: watchtower-api
    command: python3 app.py
    network_mode: host        # <-- روی خود سرویس، runtime
    env_file:
      - .env
    restart: unless-stopped
    # وقتی network_mode: host هست، دیگه networks: و ports: بی‌معنی/غیرمجازن و باید حذف بشن

  recon-tools:
    build:
      context: .
      dockerfile: xsscanner/Dockerfile
      network: host
    container_name: recon-tools
    network_mode: host        # <-- همینجا هم
    env_file:
      - .env
    depends_on:
      - watchtower-api
    volumes:
      - recon-results:/xsscanner/results
      - ./.env:/watchtower/.env:ro
      - ./.env:/xsscanner/.env:ro
      - ./.env:/.env:ro
    profiles:
      - manual

volumes:
  recon-results: