services:
  watchtower-api:
    build: 
      context: ..
      dockerfile: database/Dockerfile  # به داکر می‌گوید فایل داکرفایل داخل پوشه دیتابیس است
    container_name: watchtower-backend
    ports:
      - "3131:3131"
    environment:
      - MONGO_URI=mongodb+srv://arianapex4_db_user:q0EzEexHHakVpzdV@cluster0.mzmzk4u.mongodb.net/?appName=Cluster0
      - API_TOKEN=a21uc0lzeTcK
    restart: unless-stopped