// File: pkg/reflectctx/reflectctx_test.go
package reflectctx

import (
	"regexp"
	"strings"
	"testing"
)

func TestVerifyBreakout_DoubledQuoteRegression(t *testing.T) {
	// Real body snippet from a live vulnerable target.
	body := []byte(`... value=""x9dbgabc" ...`) // exact pattern with doubled quote before canary

	// Case 1: BARE canary (correct) -> should confirm breakout.
	confirmed, ctxType := VerifyBreakout(body, "x9dbgabc", '"')
	if !confirmed {
		t.Errorf("Expected confirmed true, got false")
	}
	if ctxType != ContextHTMLAttrQuoted {
		t.Errorf("Expected ContextHTMLAttrQuoted, got %v", ctxType)
	}

	// Case 2: FULL payload including marker (buggy) -> should NOT confirm.
	confirmed2, _ := VerifyBreakout(body, "\"x9dbgabc", '"')
	if confirmed2 {
		t.Errorf("Expected confirmed false for full payload, got true")
	}
}

func TestClassifyContext(t *testing.T) {
	tests := []struct {
		name         string
		body         string
		canary       string
		wantType     ContextType
		wantQuote    byte
		checkEscaped bool // Used to assert IsEscaped behavior for the quote exactly preceding the canary
	}{
		{
			name:      "Plain HTML quoted attribute",
			body:      `<html><body><input value="...CANARY..."></body></html>`,
			canary:    "CANARY",
			wantType:  ContextHTMLAttrQuoted,
			wantQuote: '"',
		},
		{
			name:      "JS string literal",
			body:      `<script> var x = 'foo' + "...CANARY..."; </script>`,
			canary:    "CANARY",
			wantType:  ContextJSString,
			wantQuote: '"', // The literal directly bounding the canary is "
		},
		{
			name:         "JS string literal with escaped quote",
			body:         `<script>var x = "\"CANARY";</script>`,
			canary:       "CANARY",
			wantType:     ContextJSString,
			wantQuote:    '"',
			checkEscaped: true,
		},
		{
			name:      "Escaped-looking quote pattern outside script (HTML attr)",
			body:      `<input value="\"CANARY">`,
			canary:    "CANARY",
			wantType:  ContextHTMLAttrQuoted,
			wantQuote: '"',
		},
		{
			name:      "Plain HTML body between tags",
			body:      `<div><p>CANARY</p></div>`,
			canary:    "CANARY",
			wantType:  ContextHTMLBody,
			wantQuote: 0,
		},
		{
			name:      "Unquoted attribute",
			body:      `<input value=CANARY>`,
			canary:    "CANARY",
			wantType:  ContextHTMLAttrUnquoted,
			wantQuote: 0,
		},
		{
			name:      "Unquoted attribute within query parameter of quoted attribute",
			body:      `<a href="?a=b&c=CANARY">`,
			canary:    "CANARY",
			wantType:  ContextHTMLAttrQuoted,
			wantQuote: '"',
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			idx := strings.Index(tt.body, tt.canary)
			if idx == -1 {
				t.Fatalf("canary %q not found in body", tt.canary)
			}

			if tt.checkEscaped {
				// Verify the escaped logic handles the quote right before the canary
				if !IsEscaped([]byte(tt.body), idx-1) {
					t.Errorf("expected quote at idx-1 to be marked as escaped, but it was not")
				}
			}

			got := ClassifyContext([]byte(tt.body), idx)
			if got.Type != tt.wantType {
				t.Errorf("ClassifyContext() Type = %v, want %v", got.Type, tt.wantType)
			}
			if got.QuoteChar != tt.wantQuote {
				t.Errorf("ClassifyContext() QuoteChar = %v, want %v", got.QuoteChar, tt.wantQuote)
			}
		})
	}
}

func TestRegexExtraction_BugRepro(t *testing.T) {
	// Represents the URL format generated by x9.go with a leading double-quote
	rawURL := `https://www.redeverdeamarela.com.br/?p="x9abc`

	// The old regex that failed
	oldRe := regexp.MustCompile(`x9(?:canary)?[a-z]*`)
	extractedOld := oldRe.FindString(rawURL)
	if extractedOld == "\"x9abc" {
		t.Errorf("Old regex unexpectedly passed")
	}

	// The new regex
	newRe := regexp.MustCompile(`(?:<b9|['"])?x9(?:canary)?[a-z]*(?:['"\;<{]|\{\{)?`)
	extractedNew := newRe.FindString(rawURL)
	if extractedNew != "\"x9abc" {
		t.Errorf("New regex failed to extract leading marker, got: %s", extractedNew)
	}
}

// ---------- NEW REGRESSION TESTS FOR FIX ----------

func TestClassifyContext_LeadingMarkerQuote(t *testing.T) {
	body := []byte(`<input value=""x9dbg" class="form-control">`)
	idx := strings.Index(string(body), "x9dbg")
	if idx == -1 {
		t.Fatal("canary not found")
	}
	ctx := ClassifyContext(body, idx)
	if ctx.Type != ContextHTMLAttrQuoted {
		t.Errorf("Expected ContextHTMLAttrQuoted, got %v", ctx.Type)
	}
	if ctx.QuoteChar != '"' {
		t.Errorf("Expected quote char '\"', got %v", ctx.QuoteChar)
	}

	confirmed, ctxType := VerifyBreakout(body, "x9dbg", '"')
	if !confirmed {
		t.Errorf("Expected confirmed true, got false")
	}
	if ctxType != ContextHTMLAttrQuoted {
		t.Errorf("Expected ContextHTMLAttrQuoted, got %v", ctxType)
	}
}

func TestClassifyContext_UnrelatedStrayQuote(t *testing.T) {
	// This proves the safety loop still catches a genuinely closed attribute.
	body := []byte(`<input value="foo"bar x9dbg" class="x">`)
	idx := strings.Index(string(body), "x9dbg")
	if idx == -1 {
		t.Fatal("canary not found")
	}
	ctx := ClassifyContext(body, idx)
	if ctx.Type != ContextUnknown {
		t.Errorf("Expected ContextUnknown, got %v", ctx.Type)
	}
	confirmed, _ := VerifyBreakout(body, "x9dbg", '"')
	if confirmed {
		t.Errorf("Expected confirmed false, got true")
	}
}

func BenchmarkClassifyContext(b *testing.B) {
	// Create a realistic 100KB body payload
	body := make([]byte, 100*1024)
	for i := range body {
		body[i] = ' '
	}

	// Inject the canary near the end to force backwards scanning
	copy(body[99000:], []byte("CANARY"))

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		// Target: should easily hit millions of iterations per second without GC thrash
		ClassifyContext(body, 99000)
	}
}
